# Generated by Django 2.2.6 on 2020-01-03 17:47
# This migration will need to bypass foreign key constraints
# Run SET FOREIGN_KEY_CHECKS=0; before and SET FOREIGN_KEY_CHECKS=1; after the migration

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0014_auto_20180413_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
